In [1]:
import pandas as pd

In [2]:
seoul_subway = pd.read_csv("서울교통공사_역주소 및 전화번호_20220314.csv", thousands = ',',
                                encoding = 'euc-kr')
seoul_subway

,연번,역번호,호선,역명,도로명주소,지번주소
0,1,150,1,서울,서울특별시 중구 세종대로 지하2(남대문로 5가),서울특별시 중구 남대문로5가 73-6 서울역(1호선)
1,2,151,1,시청,서울특별시 중구 세종대로 지하101(정동),서울특별시 중구 정동 5-5 시청역(1호선)
2,3,152,1,종각,서울특별시 종로구 종로 지하55(종로1가),서울특별시 종로구 종로1가 54 종각역(1호선)
3,4,153,1,종로3가,서울특별시 종로구 종로 지하129(종로3가),서울특별시 종로구 종로3가 10-5 종로3가역(1호선)
4,5,154,1,종로5가,서울특별시 종로구 종로 지하216(종로5가),서울특별시 종로구 종로5가 82-1 종로5가역(1호선)
...,...,...,...,...,...,...
283,284,4134,9,송파나루,서울특별시 송파구 백제고분로 지하446(방이동),서울특별시 송파구 방이동 2 송파나루역(9호선)
284,285,4135,9,한성백제,서울특별시 송파구 위례성대로 지하29(방이동),서울특별시 송파구 방이동 88-17 한성백제역(9호선)
285,286,4136,9,올림픽공원(한국체대),서울특별시 송파구 양재대로 지하1233(방이동),서울특별시 송파구 방이동 89-28 올림픽공원역(9호선)
286,287,4137,9,둔촌오륜,서울특별시 강동구 강동대로 지하303(둔촌동),서울특별시 강동구 둔촌동 227-7 둔촌오륜역(9호선)
287,288,4138,9,중앙보훈병원,서울특별시 강동구 동남로 지하625(둔촌동),서울특별시 강동구 둔촌동 8-1 중앙보훈병원역(9호선)

In [3]:
import googlemaps

In [4]:
gmaps_key = "AIzaSyBmPcwyuCvWDctc7afFkam67VH77-mNkPg"
gmaps = googlemaps.Client(key = gmaps_key)

In [5]:
seoul_subway_lat = [] #위도
seoul_subway_lng = [] #경도

for x in seoul_subway['도로명주소']:
    tmp = gmaps.geocode(x, language = 'ko')
    tmp_loc= tmp[0].get("geometry")

    seoul_subway_lat.append(tmp_loc['location']['lat'])
    seoul_subway_lng.append(tmp_loc['location']['lng'])

In [6]:
seoul_subway_lat

[37.5587351,
 37.5666082,
 37.5700105,
 37.570436,
 37.571031,
 37.5728396,
 37.578486,
 37.5837593,
 37.5797474,
 37.5775993,
 37.561398,
 37.5666911,
 37.5662094,
 37.5665899,
 37.5662916,
 37.5654292,
 37.56398739999999,
 37.5596331,
 37.5608641,
 37.5463387,
 37.5446813,
 37.54081559999999,
 37.5444007,
 37.5353816,
 37.5189313,
 37.52099219999999,
 37.5045774,
 37.5166152,
 37.508861,
 37.508861,
 37.500326,
 37.5000776,
 37.4910405,
 37.4910405,
 37.4870964,
 37.485622,
 37.4799015,
 37.4799015,
 37.4799015,
 37.4867897,
 37.487549,
 37.485363,
 37.4934315,
 37.5088099,
 37.518811,
 37.5265942,
 37.5346602,
 37.554252,
 37.5563194,
 37.5543865,
 37.5469511,
 37.5543934,
 37.5634497,
 37.5669045,
 37.5706952,
 37.578486,
 37.5142835,
 37.5113363,
 37.5195255,
 37.5723955,
 37.6487922,
 37.6358242,
 37.621541,
 37.61204770000001,
 37.6046138,
 37.5928868,
 37.5827071,
 37.57142109999999,
 37.574115,
 37.5772954,
 37.5720785,
 37.5664076,
 37.5587734,
 37.5605514,
 37.5587251,
 37.5457828,
 37.5400509,
 37.5263577,
 37.52106819999999,
 37.5126755,
 37.5054982,
 37.4910405,
 37.4935639,
 37.4785654,
 37.48859059999999,
 37.48859059999999,
 37.493668,
 37.493668,
 37.4881652,
 37.4881652,
 37.4874685,
 37.4956865,
 37.4919273,
 37.5041934,
 37.670607,
 37.6610573,
 37.6561147,
 37.6533776,
 37.6675936,
 37.6290856,
 37.6290856,
 37.6290856,
 37.6085948,
 37.5935975,
 37.5885903,
 37.5816314,
 37.5719508,
 37.5637333,
 37.5587734,
 37.5617173,
 37.5580788,
 37.5520713,
 37.5454036,
 37.5325443,
 37.5306984,
 37.5261469,
 37.5028599,
 37.476559,
 37.476559,
 37.490797,
 37.5750678,
 37.564519,
 37.5557019,
 37.5610725,
 37.5745847,
 37.5706297,
 37.5512896,
 37.5487046,
 37.5512896,
 37.5238539,
 37.526072,
 37.526072,
 37.5229518,
 37.5269397,
 37.5210747,
 37.517435,
 37.5213559,
 37.5234916,
 37.5389594,
 37.5511348,
 37.5544849,
 37.5624087,
 37.5680974,
 37.5722099,
 37.572586,
 37.56889,
 37.5650361,
 37.5607672,
 37.5530275,
 37.5567086,
 37.5596331,
 37.567372,
 37.5645064,
 37.564181,
 37.5505785,
 37.5505785,
 37.5408623,
 37.5443765,
 37.5443765,
 37.5396157,
 37.5490445,
 37.5490445,
 37.5560941,
 37.5570545,
 37.527657,
 37.511246,
 37.511246,
 37.5041934,
 37.4956865,
 37.4897279,
 37.4952383,
 37.5570545,
 37.5637007,
 37.5518381,
 37.5476396,
 37.5402481,
 37.595613,
 37.6005677,
 37.61204770000001,
 37.6165816,
 37.621541,
 37.6134018,
 37.595613,
 37.5841679,
 37.58214359999999,
 37.5592762,
 37.5656178,
 37.5554884,
 37.5495753,
 37.54961590000001,
 37.5452972,
 37.5497599,
 37.5491304,
 37.5395736,
 37.5329296,
 37.5305359,
 37.5342345,
 37.5339827,
 37.5587251,
 37.5587251,
 37.5607672,
 37.56731,
 37.5753626,
 37.5753626,
 37.5866501,
 37.5860125,
 37.5996623,
 37.5971779,
 37.6060997,
 37.611277,
 37.6282394,
 37.6304722,
 37.6280947,
 37.6109947,
 37.6190542,
 37.7001506,
 37.6890338,
 37.6543386,
 37.6543386,
 37.6543386,
 37.6510125,
 37.6376443,
 37.6304722,
 37.6304722,
 37.5976182,
 37.6005095,
 37.5967657,
 37.5835701,
 37.5809077,
 37.5712405,
 37.56354400000001,
 37.5505785,
 37.5471794,
 37.5463089,
 37.540458,
 37.51673170000001,
 37.51673170000001,
 37.51673170000001,
 37.51673170000001,
 37.5151065,
 37.5054982,
 37.4910405,
 37.4889312,
 37.4889312,
 37.4990513,
 37.5032626,
 37.4990513,
 37.5143563,
 37.5062327,
 37.5001413,
 37.4954266,
 37.5050823,
 37.4824123,
 37.4759465,
 37.4717061,
 37.4808353,
 37.4915106,
 37.550148,
 37.5443765,
 37.5291562,
 37.52099219999999,
 37.5149112,
 37.5024352,
 37.4956865,
 37.4956865,
 37.4855846,
 37.4768715,
 37.4768715,
 37.46306999999999,
 37.4494334,
 37.4549348,
 37.4494334,
 37.4500047,
 37.439935,
 37.4401794,
 37.5109479,
 37.51397499999999,
 37.5109479,
 37.5109479,
 37.5098432,
 37.5067945,
 37.5019016,
 37.5024352,
 37.5111692,
 37.511246,
 37.511246,
 37.5221461,
 37.5348764]

In [7]:
seoul_subway['위도'] = seoul_subway_lat
seoul_subway['경도'] = seoul_subway_lng

In [8]:
seoul_subway

,연번,역번호,호선,역명,도로명주소,지번주소,위도,경도
0,1,150,1,서울,서울특별시 중구 세종대로 지하2(남대문로 5가),서울특별시 중구 남대문로5가 73-6 서울역(1호선),37.558735,126.973859
1,2,151,1,시청,서울특별시 중구 세종대로 지하101(정동),서울특별시 중구 정동 5-5 시청역(1호선),37.566608,126.973148
2,3,152,1,종각,서울특별시 종로구 종로 지하55(종로1가),서울특별시 종로구 종로1가 54 종각역(1호선),37.570011,126.982108
3,4,153,1,종로3가,서울특별시 종로구 종로 지하129(종로3가),서울특별시 종로구 종로3가 10-5 종로3가역(1호선),37.570436,126.992148
4,5,154,1,종로5가,서울특별시 종로구 종로 지하216(종로5가),서울특별시 종로구 종로5가 82-1 종로5가역(1호선),37.571031,127.001951
...,...,...,...,...,...,...,...,...
283,284,4134,9,송파나루,서울특별시 송파구 백제고분로 지하446(방이동),서울특별시 송파구 방이동 2 송파나루역(9호선),37.511169,127.095426
284,285,4135,9,한성백제,서울특별시 송파구 위례성대로 지하29(방이동),서울특별시 송파구 방이동 88-17 한성백제역(9호선),37.511246,127.129362
285,286,4136,9,올림픽공원(한국체대),서울특별시 송파구 양재대로 지하1233(방이동),서울특별시 송파구 방이동 89-28 올림픽공원역(9호선),37.511246,127.129362
286,287,4137,9,둔촌오륜,서울특별시 강동구 강동대로 지하303(둔촌동),서울특별시 강동구 둔촌동 227-7 둔촌오륜역(9호선),37.522146,127.133775
287,288,4138,9,중앙보훈병원,서울특별시 강동구 동남로 지하625(둔촌동),서울특별시 강동구 둔촌동 8-1 중앙보훈병원역(9호선),37.534876,127.145270

In [9]:
seoul_subway.to_csv('C:/Users/USER/Desktop/seoul_subway_loc.csv', index=False)